

# -*- coding: utf-8 -*-
"""[Nicole_Lovold_Egar]Assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j5EomK04JF-H3FM_TdzSDk_US55nJd36
"""
import streamlit as st
import pandas as pd
import plotly.express as px

streamlit run london_hotels.py

st.title("Rest Easy! Find your London Hotel")
st.markdown("You're a few questions away from finding a place to stay")


val1 = st.text_input('Please describe what you are looking for in a hotel:')

hotels = df['hotel_features'].values
st.button('Show Hotels')

@st.cache(persist=True)
def load_data():
    df = pd.read_csv("https://www.kaggle.com/datasets/hamzafarooq50/hotel-listings-and-reviews?select=HotelListInLondon__en2019100120191005.csv")
    return(df)



def run():
    st.subheader("Hotels In London")

    df = load_data()



    disp_head = st.sidebar.radio('Select DataFrame Display Option:',('Head', 'All'),index=0)



    #Multi-Select
    #sel_plot_cols = st.sidebar.multiselect("Select Columns For Scatter Plot",df.columns.to_list()[0:4],df.columns.to_list()[0:2])

    #Select Box
    #x_plot = st.sidebar.selectbox("Select X-axis Column For Scatter Plot",df.columns.to_list()[0:4],index=0)
    #y_plot = st.sidebar.selectbox("Select Y-axis Column For Scatter Plot",df.columns.to_list()[0:4],index=1)


    if disp_head=="Head":
        st.dataframe(df.head())
    else:
        st.dataframe(df)
    #st.table(df)
    #st.write(df)


    #Add images
    #images = ["<image_url>"]
    #st.image(images, width=600,use_container_width=True, caption=["Iris Flower"])





if __name__ == '__main__':
    run()
